DO $$
BEGIN
  ALTER TABLE public.products ADD COLUMN IF NOT EXISTS weight_g INTEGER DEFAULT 0;
  ALTER TABLE public.products ADD COLUMN IF NOT EXISTS height_cm NUMERIC(10, 2) DEFAULT 0;
  ALTER TABLE public.products ADD COLUMN IF NOT EXISTS width_cm NUMERIC(10, 2) DEFAULT 0;
  ALTER TABLE public.products ADD COLUMN IF NOT EXISTS length_cm NUMERIC(10, 2) DEFAULT 0;
END $$;
